now it's givign The plugins `path_provider, share, sqflite, url_launcher` use a deprecated version of the Android embedding.                 To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs.                 If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.                 Launching lib/main.dart on Pixel 6 in debug mode...                 [!] Your app isn't using AndroidX.                     To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY .                 Running Gradle task 'assembleDebug'...
                Welcome to Gradle 4.10.2!

                Here are the highlights of this release:
                 - Incremental Java compilation by default
                 - Periodic Gradle caches cleanup
                 - Gradle Kotlin DSL 1.0-RC6
                 - Nested included builds
                 - SNAPSHOT plugin versions in the `plugins {}` block

                For more details see https://docs.gradle.org/4.10.2/release-notes.html

                FAILURE: Build failed with an exception.

                * Where:
                Script '/Users/neilwarner/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 464

                * What went wrong:
                A problem occurred evaluating root project 'android'.
                > A problem occurred configuring project ':app'.
                   > Could not get unknown property 'ndkVersion' for object of type com.android.build.gradle.internal.dsl.BaseAppModuleExtension.

                * Try:
                Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

                * Get more help at https://help.gradle.org

                BUILD FAILED in 30s
                Exception: Gradle task assembleDebug failed with exit code 1